# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
    ]
